# Generated by Django 5.0.2 on 2024-02-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, verbose_name='стоимость курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(default=0, verbose_name='стоимость урока'),
        ),
    ]
