# Generated by Django 4.2.10 on 2024-03-03 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_price_lesson_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='последнее обновление'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='последнее обновление'),
        ),
    ]
